### ISSUE TITLE
Spacetime publish error

### ISSUE THREAD

**Issue by Trobyss** [clockworklabs/spacetime-mud#3]
Hi,

Trying to running this project but got this error inside `./Server` file:

```zsh
spacetime-mud/Server on main via 🦀 v1.70.0 
➜ spacetime publish -c spacetime-mud
Error: No such file or directory (os error 2)
```

My Spacetime instance is running:
```
➜ spacetime start
2023-08-15T20:45:00.414247Z DEBUG crates/standalone/src/subcommands/start.rs:219: Starting SpacetimeDB listening on 127.0.0.1:3000    
```

(I following this: https://spacetimedb.com/docs/unity-tutorial/unity-tutorial-part-1: "In your terminal or command window, run the following commands. cd Server spacetime publish -c yourname-bitcraftmini")

### Version:

```sh
spacetimedb tool version 0.6.1; spacetimedb-lib version 0.6.1;
```
### Hardware Overview:
```
      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,3
      Chip: Apple M1 Pro
      Total Number of Cores: 8 (6 performance and 2 efficiency)
      Memory: 32 GB
      System Firmware Version: 8419.80.7
      OS Loader Version: 8419.80.7
```

Thanks !

Trob'

**Comment by gefjon** [comment]
Are `cargo` and `rustup` available in your path?

**Comment by Trobyss** [comment]
`rustup` wasn't installed...  thanks ;)
